Ben\DoctorsBundle\Entity\Person:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: cin
    properties:
        cin:
            - NotBlank: ~
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: cne
    properties:
        cin:
            - NotBlank: ~